apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.flowName }}-props
data:
  application.properties: |
    kogito.dataindex.http.url: "http://dataindex.{{ .Release.Namespace }}.svc.cluster.local"

