apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devmode
  name: devmode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devmode
  template:
    metadata:
      labels:
        app: devmode
    spec:
      containers:
        - name: devmode
          image: {{ .Values.image }}
          env:
            - name: KOGITO.CODEGEN.PROCESS.FAILONERROR
              value: "false"
            - name: QUARKUS_KOGITO_DEVSERVICES_ENABLED
              value: "true"
            - name: QUARKUS_DEVSERVICES_ENABLED
              value: "true"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 800m
              memory: 3G
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: sonataflow-resources
              mountPath: /home/kogito/serverless-workflow-project/src/main/resources
      volumes:
        - name: sonataflow-resources
          hostPath:
            path: /worker-share/sonataflow-devmode-resources
            type: DirectoryOrCreate
