appName: janus-idp-workflows

namespace: default

serviceAccountName: janus-idp-workflows-sa

labels:
  - app: janus-idp-workflows

flowName: starter

postgresql-persistent:
  database_service_name: workflows-db
  memory_limit: 512Mi
  namespace: default 
  volume_capacity: 1Gi
  config:
    postgresql_database: testdb
    postgresql_password: testp
    postgresql_user: testu
    port: 5432
  image:
    tag: "latest"


# override Janus image with one with the orchestrator plugin
backstage:
  upstream:
    backstage:
      image:
        repository: rgolangh/orchestrator
