apiVersion: v2
name: janus-idp-workflows
description: A Helm chart for Kubernetes
type: application
version: 0.1.3
appVersion: "0.0.1"

dependencies:
  - name: backstage
    repository: https://janus-idp.github.io/helm-backstage
    version: "2.4.0"
  - name: postgresql-persistent
    repository: https://sclorg.github.io/helm-charts
    version: "0.0.3"
    condition: postgresql-persistent.enabled
  - name: devmode
    version: 0.1.0
    repository: file://devmode
    condition: devmode.enabled
  - name: sonataflow-operator 
    version: 0.1.0
    repository: file://sonataflow-operator
    condition: sonataflow-operator.enabled
  - name: serverless-knative
    version: 0.1.0
    repository: file://serverless-knative
    condition: serverless-knative.enabled
  - name: workflows
    version: 0.1.0
    repository: file://workflows
    condition: workflows.enabled
