appName: janus-idp-workflows

global:
  # false means kind, minikube
  openshift: true
 
devmode:
  enabled: false
  image: quay.io/kiegroup/kogito-swf-devmode-nightly:main-2024-01-03

sonataflow-operator:
  enabled: true

serverless-knative:
  openshift:
    enabled: true

workflows:
  enabled: false

serviceAccountName: janus-idp-workflows-sa

labels:
  - app: janus-idp-workflows

postgresql-persistent:
  # depends on sonataflow-operator which still uses the ephemeral image. 
  enabled: false
  database_service_name: workflows-db
  memory_limit: 512Mi
  volume_capacity: 1Gi
  config:
    postgresql_database: testdb
    postgresql_password: testp
    postgresql_user: testu
    port: 5432
  image:
    tag: "latest"

# override Janus image with one with the orchestrator plugin
# May change with dynamic plugin support
backstage: 
  route:
    # set to false for kubernetes
    enabled: true
  global:
    dynamic:
      includes:
      - dynamic-plugins.default.yaml
      plugins:
      - disabled: false
        integrity: sha512-xwLJA197QiblD4ziBGP6W7Lf7VOStdyNLc+MmIarYu54ivaUh5nhucw1bLTub1jjvgIJ/2fwcmhP8lGXI79pSg==
        package: '@caponetto-tests/backstage-plugin-orchestrator-backend-dynamic@0.0.10'
        pluginConfig:
          orchestrator:
            dataIndexService:
              url: http://sonataflow-platform-data-index-service.sonataflow-infra
            editor:
              path: https://sandbox.kie.org/swf-chrome-extension/0.32.0
      - disabled: false
        integrity: sha512-7Wur8JlvVCPG9afbcTp3Cy/BLnFtep+NoL4Z6cCbeeM1MSinhT1QP+kppuu5St8LdXCShfm2WsPDaxq/mWxAtA==
        package: '@caponetto-tests/backstage-plugin-orchestrator@0.0.10'
        pluginConfig:
          dynamicPlugins:
            frontend:
              caponetto-tests.backstage-plugin-orchestrator:
                appIcons:
                - importName: OrchestratorIcon
                  module: OrchestratorPlugin
                  name: orchestratorIcon
                dynamicRoutes:
                - importName: OrchestratorPage
                  menuItem:
                    icon: orchestratorIcon
                    text: Orchestrator
                  module: OrchestratorPlugin
                  path: /orchestrator
  upstream:
    backstage:
      image:
        tag: next
      appConfig:
        integrations:
          github:
            - host: github.com
              token: "INSERT VALID TOKEN HERE"
        auth:
          environment: development
          providers:
            github:
              development:
                clientId: "INSERT VALID CLIENT ID HERE"
                clientSecret: "INSERT VALID CLIENT SECRET HERE"
        catalog:
          rules:
            - allow:
                [
                  Component,
                  System,
                  Group,
                  Resource,
                  Location,
                  Template,
                  API,
                  User,
                  Domain,
                ]
          locations:
            - type: url
              target: https://github.com/parodos-dev/workflow-software-templates/blob/main/entities/workflow-resources.yaml
            - type: url
              target: https://github.com/parodos-dev/workflow-software-templates/blob/main/template/template.yaml
            - type: url
              target: https://github.com/janus-idp/software-templates/blob/main/showcase-templates.yaml
        backend:
          csp:
            frame-src:
              - "https://sandbox.kie.org"
        orchestrator:
          catalog:
            environment: development


           
