---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dataindex
  name: dataindex
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: dataindex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dataindex
  name: dataindex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataindex
  template:
    metadata:
      labels:
        app: dataindex
    spec:
      containers:
        - name: dataindex
          image: "{{ .Values.dataindex.image }}"
          env:
            - name: KOGITO.CODEGEN.PROCESS.FAILONERROR
              value: "false"
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
              value: update
            - name: QUARKUS_KAFKA_HEALTH_ENABLE
              value: "false"
            - name: QUARKUS_HTTP_CORS
              value: "true"
            - name: QUARKUS_HTTP_CORS_ORIGINS
              value: /.*/
            - name: QUARKUS_FLYWAY_MIGRATE_AT_START 
              value: "true"
            - name: KOGITO_DATA_INDEX_QUARKUS_PROFILE 
              value: "http-events-support"
            - name: QUARKUS_HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 800m
              memory: 1G
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            httpGet:
              path: /q/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
