apiVersion: v1
kind: ConfigMap
metadata:
  name: devmode-resources
data:
  input.json: |
      {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "type": "object",
          "properties": {
            "color": {
              "type": "string"
            }
          },
          "required": [
            "color"
          ]
      }
  starter.sw.yaml: |2+
    specVersion: "0.8"
    id: starter
    annotations:
      - workflow-type/infrastructure
    dataInputSchema:
      schema: input.json
      failOnValidationErrors: false
    timeouts:
      workflowExecTimeout:
        duration: PT24H
    start: restcall
    functions:
      - name: get
        type: custom
        operation: 'rest:get:https://pokeapi.co/api/v2/version/red'
    states:
      - name: restcall
        type: operation
        actions:
          - functionRef:
              refName: get
              arguments:
                color: .color
            actionDataFilter:
              toStateData: .pokemon
        stateDataFilter:
          output: '{moredata: $WORKFLOW.instanceId,  id: .pokemon.id}'
        transition: output
      - name: output
        type: inject
        data:
          msg: hi
        stateDataFilter:
          output: '{ message: .id, result: .id}'
        end: true



