apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: {{ .Values.flowName }}
  annotations:
    sonataflow.org/description: Starter flow
    sonataflow.org/version: 0.0.1
spec:
  resources:
    configMaps:
      - configMap:
          name: openapi-specs
        workflowPath: specs
      - configMap:
          name: schemas
  flow:
      {{ .Files.Get "starter.sw.yaml" | indent 4 }}
