apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  name: {{ .Values.flowName }}
┊ annotations:
┊ ┊ sonataflow.org/description: Starter flow
┊ ┊ sonataflow.org/version: 0.0.1
spec:
┊ flow:
    specVersion: 0.8
    id: starterflow
    annotations:
      # Thie annotation will be used by backstage to customize the user experience
      - "workflow-type/infrastructure"
    version: 0.0.1
    dataInputSchema: schema/input.json
    extensions:
      - extensionid: workflow-output-schema
        outputSchema: schema/ouput.json
    resources:
      configMaps:
      ┊ - configMap:
      ┊ ┊ ┊  name: openapi-specs
      ┊ ┊ workflowPath: specs
    timeouts:
      workflowExecTimeout: PT24H
    start: restcall
    functions:
      - name: get
        type: custom
        operation: rest:get:https://pokeapi.co/api/v2/version/{color}
    states:
      - name: restcall
        type: operation
        actions:
          - functionRef:
              refName: get
              arguments:
                color: .color
            actionDataFilter:
              toStateData: .pokemon
        stateDataFilter:
          output: "{moredata: $WORKFLOW.instanceId,  id: .pokemon.id}"
        transition: output
      - name: output
        type: inject
        data:
          msg: hi
        stateDataFilter:
          output: "{ message: .id, result: .id}"
        end: true
